# Generated by Django 6.1.1 on 2026-10-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=48)),
                ("description", models.CharField(blank=True, max_length=180)),
                ("color", models.CharField(default="#5b5bd6", max_length=7)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_guilds", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="GuildMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("member", "Member")], default="member", max_length=16)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("guild", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="guilds.guild")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guild_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="guildmember",
            constraint=models.UniqueConstraint(fields=("guild", "user"), name="unique_guild_member"),
        ),
    ]
